(require 'package)
(add-to-list 'package-archives '("tromey" . "http://tromey.com/elpa/") :append)
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/") :append)
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/") :append)
(package-initialize)
(setq package-enable-at-startup nil)
